import { createClient } from "@/lib/supabase/server";
import { toApiError } from "@/lib/errors";
import { z } from "zod";
import type {
  ExistingReview,
  FeasibilityScore,
  GapAnalysis,
  StudyDesignRecommendation,
  GapDimension,
} from "@/types";

// ---------------------------------------------------------------------------
// Input validation
// ---------------------------------------------------------------------------

const emailReportSchema = z.object({
  resultId: z.string().uuid("Invalid result ID."),
  email: z.string().email("Please enter a valid email address."),
});

// ---------------------------------------------------------------------------
// Text helpers
// ---------------------------------------------------------------------------

const GAP_LABELS: Record<GapDimension, string> = {
  population: "Population",
  methodology: "Methodological",
  outcome: "Outcome",
  geographic: "Geographic",
  temporal: "Temporal",
  theoretical: "Theoretical",
};

function buildPlainTextReport(params: {
  query: string;
  primaryStudyCount: number;
  existingReviews: ExistingReview[];
  feasibilityScore: FeasibilityScore | null;
  feasibilityExplanation: string | null;
  gapAnalysis: GapAnalysis | null;
  studyDesign: StudyDesignRecommendation | null;
}): string {
  const {
    query,
    primaryStudyCount,
    existingReviews,
    feasibilityScore,
    feasibilityExplanation,
    gapAnalysis,
    studyDesign,
  } = params;

  const lines: string[] = [];

  lines.push("BLINDSPOT RESEARCH GAP REPORT");
  lines.push("==============================");
  lines.push("");
  lines.push(`Topic: ${query}`);
  lines.push(`Primary studies found: ${primaryStudyCount.toLocaleString("en-US")}`);
  lines.push(`Existing reviews found: ${existingReviews.length}`);
  if (feasibilityScore) {
    lines.push(`Feasibility: ${feasibilityScore}`);
  }
  if (feasibilityExplanation) {
    lines.push("");
    lines.push(feasibilityExplanation);
  }
  lines.push("");

  if (gapAnalysis) {
    lines.push("GAP ANALYSIS");
    lines.push("------------");
    if (gapAnalysis.overall_assessment) {
      lines.push(gapAnalysis.overall_assessment);
      lines.push("");
    }
    lines.push("Identified Gaps:");
    for (const gap of gapAnalysis.gaps) {
      lines.push(`  [${gap.importance.toUpperCase()}] ${GAP_LABELS[gap.dimension]}: ${gap.description}`);
    }
    lines.push("");

    lines.push("Suggested Review Topics:");
    for (let i = 0; i < gapAnalysis.suggested_topics.length; i++) {
      const topic = gapAnalysis.suggested_topics[i];
      lines.push(`  ${i + 1}. ${topic.title}`);
      lines.push(`     Gap type: ${GAP_LABELS[topic.gap_type]} | Feasibility: ${topic.feasibility} | ~${topic.estimated_studies.toLocaleString("en-US")} primary studies`);
      lines.push(`     ${topic.rationale}`);
    }
    lines.push("");
  }

  if (studyDesign) {
    lines.push("STUDY DESIGN RECOMMENDATION");
    lines.push("---------------------------");
    lines.push(`Recommended: ${studyDesign.primary}`);
    lines.push("");
    lines.push(studyDesign.rationale);
    if (studyDesign.steps && studyDesign.steps.length > 0) {
      lines.push("");
      lines.push("How to Conduct It:");
      studyDesign.steps.forEach((step, i) => {
        lines.push(`  ${i + 1}. ${step}`);
      });
    }
    if (studyDesign.alternatives && studyDesign.alternatives.length > 0) {
      lines.push("");
      lines.push("Alternatives:");
      for (const alt of studyDesign.alternatives) {
        lines.push(`  - ${alt.type}: ${alt.rationale}`);
      }
    }
    lines.push("");
  }

  if (existingReviews.length > 0) {
    lines.push("EXISTING SYSTEMATIC REVIEWS");
    lines.push("---------------------------");
    for (const review of existingReviews.slice(0, 20)) {
      lines.push(`• ${review.title} (${review.year || "n.d."}) – ${review.journal}`);
      if (review.doi) lines.push(`  DOI: ${review.doi}`);
      if (review.pmid) lines.push(`  PMID: ${review.pmid}`);
    }
    if (existingReviews.length > 20) {
      lines.push(`  … and ${existingReviews.length - 20} more`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("AI-generated analysis — verify all findings with domain expertise before use.");
  lines.push("Generated by Blindspot");

  return lines.join("\n");
}

function buildHtmlEmail(params: {
  query: string;
  primaryStudyCount: number;
  existingReviews: ExistingReview[];
  feasibilityScore: FeasibilityScore | null;
  feasibilityExplanation: string | null;
  gapAnalysis: GapAnalysis | null;
  studyDesign: StudyDesignRecommendation | null;
}): string {
  const {
    query,
    primaryStudyCount,
    existingReviews,
    feasibilityScore,
    feasibilityExplanation,
    gapAnalysis,
    studyDesign,
  } = params;

  const FEASIBILITY_COLORS: Record<string, string> = {
    High: "#15803d",
    Moderate: "#d97706",
    Low: "#ea580c",
    Insufficient: "#dc2626",
  };

  const feasColor = feasibilityScore ? (FEASIBILITY_COLORS[feasibilityScore] ?? "#374151") : "#374151";

  // Top gaps for the header section (at most 3 high-importance)
  const topGaps = gapAnalysis?.gaps.filter((g) => g.importance === "high").slice(0, 3) ?? [];
  // Top suggested topics for email preview (at most 3)
  const previewTopics = gapAnalysis?.suggested_topics.slice(0, 3) ?? [];

  const topGapChips = topGaps
    .map(
      (g) =>
        `<span style="display:inline-block;background:#fef3c7;color:#92400e;border:1px solid #fde68a;border-radius:9999px;padding:2px 10px;font-size:12px;margin:2px 4px 2px 0;">${GAP_LABELS[g.dimension]}</span>`
    )
    .join("");

  const gapRows = (gapAnalysis?.gaps ?? [])
    .map((gap) => {
      const dotColor =
        gap.importance === "high" ? "#dc2626" : gap.importance === "medium" ? "#d97706" : "#9ca3af";
      return `<tr>
        <td style="padding:8px 12px;border-bottom:1px solid #f3f4f6;vertical-align:top;white-space:nowrap;">
          <span style="display:inline-flex;align-items:center;gap:4px;font-size:12px;color:#374151;">
            <span style="display:inline-block;width:8px;height:8px;border-radius:50%;background:${dotColor};flex-shrink:0;"></span>
            ${GAP_LABELS[gap.dimension]}
          </span>
        </td>
        <td style="padding:8px 12px;border-bottom:1px solid #f3f4f6;font-size:13px;color:#374151;">${gap.description}</td>
      </tr>`;
    })
    .join("");

  const topicCards = previewTopics
    .map(
      (topic, i) => `
    <tr>
      <td style="padding:12px;background:#f9fafb;border-radius:8px;margin-bottom:8px;display:block;">
        <p style="margin:0 0 4px 0;font-size:14px;font-weight:600;color:#1e3a5f;">${i + 1}. ${topic.title}</p>
        <p style="margin:0 0 6px 0;font-size:12px;color:#6b7280;">${GAP_LABELS[topic.gap_type]} gap · ${topic.feasibility} feasibility · ~${topic.estimated_studies.toLocaleString("en-US")} primary studies</p>
        <p style="margin:0;font-size:13px;color:#374151;">${topic.rationale}</p>
      </td>
    </tr>`
    )
    .join("<tr><td style='height:8px'></td></tr>");

  const stepsHtml = studyDesign?.steps
    ? studyDesign.steps
        .map((step, i) => `<li style="margin-bottom:6px;font-size:13px;color:#374151;">${i + 1}. ${step}</li>`)
        .join("")
    : "";

  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Blindspot Report</title></head>
<body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f3f4f6;padding:24px 0;">
    <tr><td align="center">
      <table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;">

        <!-- Header -->
        <tr><td style="background:#1e3a5f;border-radius:8px 8px 0 0;padding:24px 32px;">
          <p style="margin:0;font-size:12px;color:#93c5fd;letter-spacing:0.1em;text-transform:uppercase;">Research Gap Report</p>
          <h1 style="margin:4px 0 0 0;font-size:22px;font-weight:700;color:#ffffff;">Blindspot</h1>
        </td></tr>

        <!-- Body -->
        <tr><td style="background:#ffffff;padding:32px;border-radius:0 0 8px 8px;">

          <!-- Query -->
          <p style="margin:0 0 4px 0;font-size:11px;color:#9ca3af;text-transform:uppercase;letter-spacing:0.08em;">Topic searched</p>
          <p style="margin:0 0 24px 0;font-size:16px;font-weight:600;color:#1e3a5f;">${query}</p>

          <!-- Stats row -->
          <table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:24px;">
            <tr>
              <td style="padding:12px;background:#f9fafb;border-radius:8px;text-align:center;width:33%;">
                <p style="margin:0;font-size:22px;font-weight:700;color:#1e3a5f;">${primaryStudyCount.toLocaleString("en-US")}</p>
                <p style="margin:4px 0 0 0;font-size:11px;color:#6b7280;">Primary studies</p>
              </td>
              <td style="width:8px;"></td>
              <td style="padding:12px;background:#f9fafb;border-radius:8px;text-align:center;width:33%;">
                <p style="margin:0;font-size:22px;font-weight:700;color:#1e3a5f;">${existingReviews.length}</p>
                <p style="margin:4px 0 0 0;font-size:11px;color:#6b7280;">Existing reviews</p>
              </td>
              ${
                feasibilityScore
                  ? `<td style="width:8px;"></td>
              <td style="padding:12px;background:#f9fafb;border-radius:8px;text-align:center;width:33%;">
                <p style="margin:0;font-size:22px;font-weight:700;color:${feasColor};">${feasibilityScore}</p>
                <p style="margin:4px 0 0 0;font-size:11px;color:#6b7280;">Feasibility</p>
              </td>`
                  : `<td></td>`
              }
            </tr>
          </table>

          ${feasibilityExplanation ? `<p style="margin:0 0 24px 0;font-size:13px;color:#4b5563;line-height:1.6;">${feasibilityExplanation}</p>` : ""}

          ${
            topGaps.length > 0
              ? `<!-- Key gaps chips -->
          <div style="background:#fffbeb;border:1px solid #fde68a;border-radius:8px;padding:12px 16px;margin-bottom:24px;">
            <p style="margin:0 0 8px 0;font-size:11px;font-weight:600;color:#92400e;text-transform:uppercase;letter-spacing:0.08em;">Key gaps identified</p>
            <div>${topGapChips}</div>
          </div>`
              : ""
          }

          ${
            gapAnalysis
              ? `<!-- Gap Analysis -->
          <h2 style="margin:0 0 8px 0;font-size:15px;font-weight:600;color:#1e3a5f;border-bottom:2px solid #e5e7eb;padding-bottom:8px;">Gap Analysis</h2>
          ${gapAnalysis.overall_assessment ? `<p style="margin:0 0 16px 0;font-size:13px;color:#4b5563;line-height:1.6;">${gapAnalysis.overall_assessment}</p>` : ""}
          <table width="100%" cellpadding="0" cellspacing="0" style="border:1px solid #e5e7eb;border-radius:8px;overflow:hidden;margin-bottom:24px;">
            ${gapRows}
          </table>

          <h3 style="margin:0 0 12px 0;font-size:14px;font-weight:600;color:#1e3a5f;">Suggested Review Topics</h3>
          <table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:24px;">
            ${topicCards}
          </table>`
              : ""
          }

          ${
            studyDesign
              ? `<!-- Study Design -->
          <h2 style="margin:0 0 12px 0;font-size:15px;font-weight:600;color:#1e3a5f;border-bottom:2px solid #e5e7eb;padding-bottom:8px;">Recommended Study Design</h2>
          <p style="margin:0 0 8px 0;font-size:16px;font-weight:700;color:#4a90d9;">${studyDesign.primary}</p>
          <p style="margin:0 0 16px 0;font-size:13px;color:#4b5563;line-height:1.6;">${studyDesign.rationale}</p>
          ${
            stepsHtml
              ? `<p style="margin:0 0 8px 0;font-size:13px;font-weight:600;color:#374151;">How to Conduct It:</p>
          <ol style="margin:0 0 24px 0;padding-left:0;list-style:none;">${stepsHtml}</ol>`
              : ""
          }
          ${
            studyDesign.alternatives && studyDesign.alternatives.length > 0
              ? `<p style="margin:0 0 8px 0;font-size:12px;color:#6b7280;">Alternatives: ${studyDesign.alternatives.map((a) => a.type).join(", ")}</p>`
              : ""
          }`
              : ""
          }

          <!-- Disclaimer -->
          <div style="border-top:1px solid #e5e7eb;margin-top:24px;padding-top:16px;">
            <p style="margin:0;font-size:11px;color:#9ca3af;line-height:1.6;">
              AI-generated analysis — verify all findings with domain expertise before use in academic work.
              Results sourced from PubMed, OpenAlex, and Europe PMC.
            </p>
          </div>

        </td></tr>

        <!-- Footer -->
        <tr><td style="padding:16px 32px;text-align:center;">
          <p style="margin:0;font-size:11px;color:#9ca3af;">Generated by <strong>Blindspot</strong></p>
        </td></tr>

      </table>
    </td></tr>
  </table>
</body>
</html>`;
}

// ---------------------------------------------------------------------------
// Route handler
// ---------------------------------------------------------------------------

export async function POST(request: Request) {
  try {
    // Check Resend is configured
    const resendKey = process.env.RESEND_API_KEY;
    if (!resendKey) {
      return Response.json(
        { error: "Email delivery is not configured. Please contact the site administrator." },
        { status: 503 }
      );
    }

    // Auth check
    const supabase = await createClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();
    if (!user) {
      return Response.json({ error: "Please sign in to email a report." }, { status: 401 });
    }

    // Validate input
    const body = await request.json() as unknown;
    const parsed = emailReportSchema.safeParse(body);
    if (!parsed.success) {
      const firstIssue = parsed.error.issues[0];
      return Response.json({ error: firstIssue?.message ?? "Invalid request." }, { status: 400 });
    }
    const { resultId, email } = parsed.data;

    // Fetch result (RLS ensures it belongs to this user)
    const { data: result, error: fetchError } = await supabase
      .from("search_results")
      .select(`
        id,
        primary_study_count,
        existing_reviews,
        feasibility_score,
        feasibility_explanation,
        gap_analysis,
        study_design_recommendation,
        searches (query_text)
      `)
      .eq("id", resultId)
      .single();

    if (fetchError || !result) {
      return Response.json({ error: "Result not found." }, { status: 404 });
    }

    const query =
      (result.searches as unknown as { query_text: string } | null)?.query_text ?? "Research topic";
    const primaryStudyCount = result.primary_study_count as number;
    const existingReviews = (result.existing_reviews ?? []) as ExistingReview[];
    const feasibilityScore = result.feasibility_score as FeasibilityScore | null;
    const feasibilityExplanation = result.feasibility_explanation as string | null;
    const gapAnalysis = result.gap_analysis as GapAnalysis | null;
    const studyDesign = result.study_design_recommendation as StudyDesignRecommendation | null;

    // Build email content
    const reportParams = {
      query,
      primaryStudyCount,
      existingReviews,
      feasibilityScore,
      feasibilityExplanation,
      gapAnalysis,
      studyDesign,
    };

    const htmlBody = buildHtmlEmail(reportParams);
    const plainText = buildPlainTextReport(reportParams);

    // Encode plain-text report as base64 attachment
    const attachmentContent = Buffer.from(plainText, "utf-8").toString("base64");
    const safeTitle = query.slice(0, 40).replace(/[^a-zA-Z0-9 _-]/g, "").trim().replace(/\s+/g, "_");
    const attachmentFilename = `blindspot_report_${safeTitle || "report"}.txt`;

    // Send via Resend REST API (no npm package needed)
    const resendResponse = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${resendKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: "Blindspot <reports@blindspot.app>",
        to: [email],
        subject: `Your Blindspot report: ${query.slice(0, 60)}`,
        html: htmlBody,
        text: plainText,
        attachments: [
          {
            filename: attachmentFilename,
            content: attachmentContent,
          },
        ],
      }),
    });

    if (!resendResponse.ok) {
      const errBody = await resendResponse.json().catch(() => ({})) as { message?: string };
      console.error("[email-report] Resend error:", resendResponse.status, errBody);
      return Response.json(
        { error: "Failed to send email. Please try again later." },
        { status: 502 }
      );
    }

    return Response.json({ success: true });
  } catch (error) {
    const apiError = toApiError(error);
    return Response.json({ error: apiError.userMessage }, { status: apiError.statusCode });
  }
}
